## 
#  Altertum Travis configuration file for Linux CI
#  Copyright (c) 2015 Jonathan Howard
## 

sudo: false
dist: trusty

language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

env:
  - BCONF=debug
  - BCONF=release

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libx11-dev
      - libgl1-mesa-dev
      - libopencl1
      - opencl-headers
      - gcc-4.9
      - g++-4.9
      - clang

matrix:
  fast_finish: true # finish build as soon as job fails

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ "$CC" == "gcc" ]; then export COMPILER=gcc CC=gcc-4.9 CXX=g++-4.9; fi
  - if [ "$CC" == "clang" ]; then export COMPILER=clang; fi
  - $CXX --version

script: make -e $TRAVIS_OS_NAME-$COMPILER $TRAVIS_OS_NAME-$BCONF
