## 
#  Altertum Travis configuration file for Linux CI
#  Copyright (c) 2015 Jonathan Howard
## 

sudo: false

language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

env:
  - BCONF=debug
  - BCONF=release

matrix:
  fast_finish: true # finish build as soon as job fails
  include: 
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libx11-dev
            - libgl1-mesa-dev
            - g++-4.9
      env: 
        - COMPILER=gcc
      before_install:
        - export COMPILER=gcc
        - export CC=gcc-4.9
        - export CXX=g++-4.9
    - compiler: clang
      env:
        - COMPILER=clang

before_install:
  - echo $LANG
  - echo $LC_ALL

script: make $TRAVIS_OS_NAME-$COMPILER $TRAVIS_OS_NAME-$BCONF
